In [52]:
import numpy as np
import pandas as pd

from load_data import load_train_data,load_test_data
from sklearn.linear_model import LogisticRegression
import sklearn.preprocessing as sp

TRAIN_DATA='./train.csv'
TEST_DATA='./test.csv'

def load_train_data():
    df = pd.read_csv(TRAIN_DATA)
    return df

def load_test_data():
    df = pd.read_csv(TEST_DATA)
    return df

df = load_train_data()
# x_train = df.drop(['Survived', 'Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1)
x_train = df.loc[:['Sex']]
y_train = df['Survived'].values

In [53]:
# 性別を数字に変換
le = sp.LabelEncoder()
le.fit(x_train.Sex.unique())

LabelEncoder()

In [54]:
x_train.Sex.unique()

array(['male', 'female'], dtype=object)

In [55]:
x_train.Sex = le.fit_transform(x_train.Sex)
x_train.Sex.unique()

array([1, 0], dtype=int64)

In [56]:
# 性別をonehot表現に
one = sp.OneHotEncoder()
#1×ｎ→n×1
enced = one.fit_transform(x_train.Sex.values.reshape(1, -1).transpose())  
temp = pd.DataFrame(index=df.Sex.index, columns='Sex-' + le.classes_, data=enced.toarray())
temp

C:\Users\kenmei\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

     Sex-female  Sex-male
0           0.0       1.0
1           1.0       0.0
2           1.0       0.0
3           1.0       0.0
4           0.0       1.0
5           0.0       1.0
6           0.0       1.0
7           0.0       1.0
8           1.0       0.0
9           1.0       0.0
10          1.0       0.0
11          1.0       0.0
12          0.0       1.0
13          0.0       1.0
14          1.0       0.0
15          1.0       0.0
16          0.0       1.0
17          0.0       1.0
18          1.0       0.0
19          1.0       0.0
20          0.0       1.0
21          0.0       1.0
22          1.0       0.0
23          0.0       1.0
24          1.0       0.0
25          1.0       0.0
26          0.0       1.0
27          0.0       1.0
28          1.0       0.0
29          0.0       1.0
..          ...       ...
861         0.0       1.0
862         1.0       0.0
863         1.0       0.0
864         0.0       1.0
865         1.0       0.0
866         1.0       0.0
867         0.0       1.0
868         0.0       1.0
869         0.0       1.0
870         0.0       1.0
871         1.0       0.0
872         0.0       1.0
873         0.0       1.0
874         1.0       0.0
875         1.0       0.0
876         0.0       1.0
877         0.0       1.0
878         0.0       1.0
879         1.0       0.0
880         1.0       0.0
881         0.0       1.0
882         1.0       0.0
883         0.0       1.0
884         0.0       1.0
885         1.0       0.0
886         0.0       1.0
887         1.0       0.0
888         1.0       0.0
889         0.0       1.0
890         0.0       1.0

[891 rows x 2 columns]

In [57]:
enced_data = pd.concat([x_train, temp], axis=1)
enced_data

     Sex  Sex-female  Sex-male
0      1         0.0       1.0
1      0         1.0       0.0
2      0         1.0       0.0
3      0         1.0       0.0
4      1         0.0       1.0
5      1         0.0       1.0
6      1         0.0       1.0
7      1         0.0       1.0
8      0         1.0       0.0
9      0         1.0       0.0
10     0         1.0       0.0
11     0         1.0       0.0
12     1         0.0       1.0
13     1         0.0       1.0
14     0         1.0       0.0
15     0         1.0       0.0
16     1         0.0       1.0
17     1         0.0       1.0
18     0         1.0       0.0
19     0         1.0       0.0
20     1         0.0       1.0
21     1         0.0       1.0
22     0         1.0       0.0
23     1         0.0       1.0
24     0         1.0       0.0
25     0         1.0       0.0
26     1         0.0       1.0
27     1         0.0       1.0
28     0         1.0       0.0
29     1         0.0       1.0
..   ...         ...       ...
861    1         0.0       1.0
862    0         1.0       0.0
863    0         1.0       0.0
864    1         0.0       1.0
865    0         1.0       0.0
866    0         1.0       0.0
867    1         0.0       1.0
868    1         0.0       1.0
869    1         0.0       1.0
870    1         0.0       1.0
871    0         1.0       0.0
872    1         0.0       1.0
873    1         0.0       1.0
874    0         1.0       0.0
875    0         1.0       0.0
876    1         0.0       1.0
877    1         0.0       1.0
878    1         0.0       1.0
879    0         1.0       0.0
880    0         1.0       0.0
881    1         0.0       1.0
882    0         1.0       0.0
883    1         0.0       1.0
884    1         0.0       1.0
885    0         1.0       0.0
886    1         0.0       1.0
887    0         1.0       0.0
888    0         1.0       0.0
889    1         0.0       1.0
890    1         0.0       1.0

[891 rows x 3 columns]

In [58]:
del enced_data['Sex']

In [59]:
enced_data

     Sex-female  Sex-male
0           0.0       1.0
1           1.0       0.0
2           1.0       0.0
3           1.0       0.0
4           0.0       1.0
5           0.0       1.0
6           0.0       1.0
7           0.0       1.0
8           1.0       0.0
9           1.0       0.0
10          1.0       0.0
11          1.0       0.0
12          0.0       1.0
13          0.0       1.0
14          1.0       0.0
15          1.0       0.0
16          0.0       1.0
17          0.0       1.0
18          1.0       0.0
19          1.0       0.0
20          0.0       1.0
21          0.0       1.0
22          1.0       0.0
23          0.0       1.0
24          1.0       0.0
25          1.0       0.0
26          0.0       1.0
27          0.0       1.0
28          1.0       0.0
29          0.0       1.0
..          ...       ...
861         0.0       1.0
862         1.0       0.0
863         1.0       0.0
864         0.0       1.0
865         1.0       0.0
866         1.0       0.0
867         0.0       1.0
868         0.0       1.0
869         0.0       1.0
870         0.0       1.0
871         1.0       0.0
872         0.0       1.0
873         0.0       1.0
874         1.0       0.0
875         1.0       0.0
876         0.0       1.0
877         0.0       1.0
878         0.0       1.0
879         1.0       0.0
880         1.0       0.0
881         0.0       1.0
882         1.0       0.0
883         0.0       1.0
884         0.0       1.0
885         1.0       0.0
886         0.0       1.0
887         1.0       0.0
888         1.0       0.0
889         0.0       1.0
890         0.0       1.0

[891 rows x 2 columns]

In [60]:
from sklearn.preprocessing import Imputer
im = Imputer(missing_values='NaN', strategy='mean', axis=0)
enced_data = im.fit_transform(enced_data)

C:\Users\kenmei\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [61]:
enced_data[5]

array([0., 1.])

In [62]:
# ロジスティック回帰を使用
clf = LogisticRegression(random_state=0)
# 学習
clf.fit(enced_data, y_train)

C:\Users\kenmei\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [79]:
# テストデータの読み込み
df_test = load_test_data()
# x_test = df_test.drop(['Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1)
x_test = df_test.loc[:,['Sex']]
x_test.Sex = le.fit_transform(x_test.Sex)
enced_test = one.fit_transform(x_test.Sex.values.reshape(1, -1).transpose())
temp_test = pd.DataFrame(index=df_test.Sex.index, columns='Sex-' + le.classes_, data=enced_test.toarray())
enced_data_test = pd.concat([x_test, temp_test], axis=1)
del enced_data_test['Sex']
enced_data_test
# im = Imputer(missing_values='NaN', strategy='mean', axis=0)
# enced_data_test = im.fit_transform(enced_data_test)
# テスト
pred_test = clf.predict(enced_data_test)

df_result = pd.read_csv('./gender_submission.csv')
act = df_result['Survived']
ac = np.sum(pred_test == act ) / len(pred_test)
print(ac)

1.0

C:\Users\kenmei\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)